version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm i -g typescript
      - npm i -g @nestjs/cli
  pre_build:
    commands:
      - npm install
      - npm run test
      - npx prisma migrate dev --name init
      - npx serverless deploy
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
    - 'package.json'