version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo starting now
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run test
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/'