service: api-node-generate

provider:
  name: aws
  runtime: nodejs20.x
  deploymentBucket:
    name: my-deployment-bucket-lambda

plugins:
  - serverless-plugin-typescript

custom:
  typescript:
    tsconfig: ./tsconfig.json

functions:
  new-user:
    handler: serverless/generateExample.handler
    events:
      - schedule: rate(1 hour)