service: api-node-generate

provider:
  name: aws
  runtime: nodejs20.x
  deploymentBucket:
    name: my-deployment-bucket-lambda

plugins:
  - serverless-functions-base-path

custom:
  functionsBasePath: dist/serverless

functions:
  new-user:
    handler: generateExample.handler
    events:
      - schedule: rate(1 hour)