service: api-node-generate

provider:
  name: aws
  runtime: nodejs20.x
  deploymentBucket:
    name: my-deployment-bucket-lambda

custom:
  app: serverless

functions:
  new-user:
    handler: generateExample.handler
    events:
      - schedule: rate(1 hour)