service: api-node-generate

provider:
  name: aws
  runtime: nodejs20.x
  deploymentBucket:
    name: my-deployment-bucket-lambda

functions:
  new-user:
    handler: serverless/dist/generateExample.handler
    events:
      - schedule: rate(1 hour)